### ISSUE TITLE
Check if simple schema is already attached

### ISSUE THREAD

**Issue by xumx** [JackAdams/meteor-transactions#10]
Need a better check for whether there is a simple schema already attached.

Collections created by third-party library gets 'extended' c2 options even though they have no schema attached. Causing original fields to be filtered out during insert/update. There is no way to pass in the c2 option {filter: false} during inserts and update.

Related issue:
https://github.com/aldeed/meteor-collection2/issues/186

**Comment by xumx** [comment]
Can you do a version bump?

**Comment by JackAdams** [comment]
Yep, will do soon.  Having trouble with accessing my remote git repo.  Working on it ...

**Comment by JackAdams** [comment]
Try that out.  Having some issues with git and ssh, so hopefully got the right thing published.
