### ISSUE TITLE
ServerTime is not defined

### ISSUE THREAD

**Issue by NickBusey** [JackAdams/meteor-transactions#102]
I have been using this package for a while with no problems. I recently updated my meteor project and am now getting the following error when trying to finish a transaction.

```
I20190506-16:26:05.656(-6)? Transaction (bTMw98CmokjkxJsnz) was cancelled after being inactive for 5 seconds.
I20190506-16:26:05.660(-6)? Exception in setTimeout callback: ReferenceError: ServerTime is not defined
I20190506-16:26:05.660(-6)?     at Transact.rollback (packages/babrahams_transactions.js:733:174)
I20190506-16:26:05.660(-6)?     at onTimeOut (packages/babrahams_transactions.js:1340:12)
I20190506-16:26:05.660(-6)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190506-16:26:05.661(-6)?     at packages/meteor.js:620:25
I20190506-16:26:05.661(-6)?     at runWithEnvironment (packages/meteor.js:1356:24)
```

**Comment by JackAdams** [comment]
Hi Nick,
Sorry about the extremely late reply.  At some stage, [socialize:server-time package](https://github.com/copleykj/socialize-server-time) (which this package has as a dependency) changed from exporting globals to exporting variables that need to be imported, modern JS style.
I was lazy and [pinned the dependency](https://github.com/JackAdams/meteor-transactions/blob/a2b71764227ee7796c8dc54e72dc090725333ab5/package.js#L19) to the last old style version of the `socialize:server-time` package.
Are you, by any chance, using the latest version of `socialize:server-time` in the same project?
Brent

**Comment by NickBusey** [comment]
Yea I think I ended up pinning the older version. Good to go now, thanks.
