### ISSUE TITLE
Factor out the undo/redo into a separate package

### ISSUE THREAD

**Issue by JackAdams** [JackAdams/meteor-transactions#20]
To allow people to write their own implementations of an undo/redo stack on top of the base transactions package.

**Comment by ericoe** [comment]
I think issue #27 might be a dupe of this.

**Comment by JackAdams** [comment]
Doing this would help with some elements of doing the things described in #27.  In particular, making a custom undo/redo handler that could target particular threads. (It would just be a case of forking the `undo-redo` package and making the necessary changes.)

I actually have this factored out into two separate packages on my dev machine, but haven't released to atmosphere yet as it's a breaking changes for anyone using `babrahams:transactions`.  It would require users of the package to do `meteor add babrahams:undo-redo` to get the app back to the previous state.

**Comment by JackAdams** [comment]
Closed by 0.7.0
