### ISSUE TITLE
Package.js version is 0.6.16 but atmosphere package at 0.6.17

### ISSUE THREAD

**Issue by rjsmith** [JackAdams/meteor-transactions#22]
Hi,
The latest package on atmosphere is 0.6.17, but the committed package.js has 0.6.16.   I'm a bit confused exactly what version has been pushed to atmosphere?

**Comment by JackAdams** [comment]
Both are supposed to be 0.6.17 - the atmosphere version is and, code-wise, so is the github version.  I just forgot to push a version-bump commit.  Both should match now.
