### ISSUE TITLE
Does it work with Meteor.users? Doesn't seem to be the case

### ISSUE THREAD

**Issue by yanndebelgique** [JackAdams/meteor-transactions#23]

**Comment by JackAdams** [comment]
Let me check. I'll get back to you soon.

**Comment by JackAdams** [comment]
Seems to be working all right.  Do you have a code example where it's not working?

**Comment by yanndebelgique** [comment]
Sorry for late reply ... I didn't keep the code. I moved on and decided to just activate and reactivate the document.
