### ISSUE TITLE
Removed autopublish and now transactions don't work

### ISSUE THREAD

**Issue by davidynamic** [JackAdams/meteor-transactions#29]
Once I do "meteor remove autopublish" on my app that includes "babrahams:transactions", the "undo..." and "redo..." buttons disappear. In fact, they do appear whenever I make a change but only for a split second and then disappear. I'm using this in conjunction with babrahams:editable-text-wysiwyg-bootstrap-3

**Comment by davidynamic** [comment]
Found the answer. You need to subscribe to transactions

**Comment by JackAdams** [comment]
That's strange.  The package should manage the subscription itself, independent of iron router.
