### ISSUE TITLE
"User must be logged in to start a transaction."

### ISSUE THREAD

**Issue by VanHumbeeckA** [JackAdams/meteor-transactions#31]
"User must be logged in to start a transaction."
I get this "warning message" when executing a transaction in a method on the server.
In my transaction, I create a user along with some other samples, so no user can be logged in at that moment.

Why is it necessary to have a user logged in, when trying to execute a transaction? I don't see the point.

**Comment by JackAdams** [comment]
Yeah... this was originally a package to expose a client-side undo-redo stack that is user specific, hence the need for the user.

Putting
```
tx.requireUser = false;
``
in a file that's common to both client and server should fix things up.

**Comment by VanHumbeeckA** [comment]
Ok, thanks for clearing that up.
