### ISSUE TITLE
Updating previously-null property throws a TypeError

### ISSUE THREAD

**Issue by rjsmith** [JackAdams/meteor-transactions#34]
Found in 0.7.2

If a transaction is committed which attempts to `$set` a property on a collection document that was previously `null`, meteor-transactions throws a `[TypeError: Cannot read property 'json' of null]` error.

I added a console.log in the `_unpackageForUpdate` method:
```javascript
Transact.prototype._unpackageForUpdate = function (data) {;
  var objForUpdate = {};
  console.log('unpacking data'+JSON.stringify(data));
  _.each(data, function (val) {
    var unpackagedValue;
    if (val.value.json) {
      unpackagedValue = JSON.parse(val.value.json);
    } else {
      unpackagedValue = val.value;
    }
    objForUpdate[val.key] = unpackagedValue;
  });
  return objForUpdate;
}
```

Running the test below shows that the 2nd call to this fn does not have a 'value' property

```
I20150806-13:42:16.319(1)? Started "insert transaction" with transaction_id: CiwJHsbaxd7hnig6Y
I20150806-13:42:16.322(1)? Pushed insert command to stack: CiwJHsbaxd7hnig6Y
I20150806-13:42:16.324(1)? Beginning commit with transaction_id: CiwJHsbaxd7hnig6Y
I20150806-13:42:16.383(1)? [velocity] Established connection with Velocity.
I20150806-13:42:16.392(1)? Executed insert
I20150806-13:42:16.407(1)? Commit reset transaction manager to clean state
I20150806-13:42:16.410(1)? Started "update transaction" with transaction_id: BwnmWxLhkwyQM9xzC
I20150806-13:42:16.426(1)? Pushed update command to stack: BwnmWxLhkwyQM9xzC
I20150806-13:42:16.426(1)? Beginning commit with transaction_id: BwnmWxLhkwyQM9xzC
I20150806-13:42:16.433(1)? unpacking data[{"key":"bar","value":"updated"}]
I20150806-13:42:16.433(1)? unpacking data[{"key":"bar","value":null}]
I20150806-13:42:16.438(1)? [TypeError: Cannot read property 'json' of null]
I20150806-13:42:21.429(1)? Transaction (BwnmWxLhkwyQM9xzC) was cancelled after being inactive for 5 seconds.
I20150806-13:42:21.432(1)? Rollback reset transaction manager to clean state
```

```javascript
'use strict';

describe('committable actions', function () {

  var transaction_id, insertedFooDoc, transactionDoc, fakeId;

  beforeEach(function () {

    // Fake userId to get through tx userId checks
    fakeId = 'or6YSgs6nT8Bs5o6p';

    // Because `tx.requireUser = true` (by default)
    spyOn(Meteor,'userId').and.returnValue(fakeId);

  });

  afterEach(function () {
    fooCollection.remove({});
    tx.Transactions.remove({});
  });

  fit ('update previously null property', function () {

    // SETUP
    tx.start('insert transaction');
    fooCollection.insert(
      {foo: 'inserted', bar: null}, {tx: true});
    tx.commit();

    var savedDoc = fooCollection.findOne({foo: 'inserted'});
    expect(savedDoc).toBeDefined();
    expect(savedDoc._id).not.toBeNull();
    // EXECUTE
    tx.start('update transaction');
    fooCollection.update({_id: savedDoc._id}, {
      $set: {
        bar: 'updated'
      }
    },
    {
      tx: true
    });
    tx.commit();

    // VERIFY
    var updatedDoc = fooCollection.findOne({_id: savedDoc._id});
    expect(updatedDoc).toBeDefined();
    expect(updatedDoc.bar).toEqual('updated');

  })

});
```

**Comment by JackAdams** [comment]
Again, I can't thank you enough for submitting these bug reports with tests.  It makes my life so much easier!!!  I'm working on fixes and hope to have a new release out in an hour or two.

**Comment by rjsmith** [comment]
thanks. I am working on a repo for a 3rd bug, so please hold off pushing a
new version.  It is related to updating docs in collections that have a
transform to a object on them.

**Comment by JackAdams** [comment]
Okay, thanks for the heads up.  I've just got all tests passing and was about to release a new version.
Two things:
1) You are really thorough! (How did you find all those bugs?!!)
2) This was a lot sloppier piece of work from me than I'd hoped it would be :-p

**Comment by JackAdams** [comment]
Richard, do you mind if I release a version now with the fixes for #33 and #34 and another tomorrow with the fixes for the problem you've described?  It's getting late here and I need to go to bed, but those bugs seem serious enough that they should be dealt with now rather than tomorrow.

**Comment by rjsmith** [comment]
Hi,
OK, turns out the transform problem was in my own code .. not sure why it
didn't hit problems in the previous meteor-transactions codebase. The
problem was that the `$set` object contained object functions (from its
prototype), which then screwed up the later unpacking.  So, please release
the new version and I'll re-test the first 2 bugs.
re: how I found the bugs .. I have 200 + server integration tests in my
app, and lots of them failed as soon as I updated to 0.7.1 (from 0.6.9).
Just been going through them to isolate what has changed.

**Comment by JackAdams** [comment]
Oh man ... I feel guilty now, breaking all your tests.  Thank you so much for getting me started on the automated testing path -- lets me sleep easier at night.

About those transforms ... it's actually a legitimate concern.  This package should use untransformed docs in certain places and leave the transforms in other places (e.g. when doing permission checking).  I'm going to make a couple of changes before releasing the new version that deal with this.

**Comment by JackAdams** [comment]
On second thought ... all tests are passing.  It's late.  I'm just going to release the latest version and think about dealing with transforms later.

**Comment by rjsmith** [comment]
awesome!  All my automated tests now pass again  :-)
