### ISSUE TITLE
Conflict when the app already contains a `Transactions` collection

### ISSUE THREAD

**Issue by plbrault** [JackAdams/meteor-transactions#36]
When an app already defines a MongoDB collection named `transactions`, the developers are forced to change its name after installing the package. I think that the collection created by the package should be renamed to something that is not a plain dictionary word to avoid any conflict.

**Comment by JackAdams** [comment]
Good point. There might be some backwards compatibility concerns doing this, but you're right - the collection name should be prefixed with an underscore at least.

**Comment by ericoe** [comment]
How about a config setting to chg name?

**Comment by stivaugoin** [comment]
Good idea @ericoe

**Comment by JackAdams** [comment]
Agreed. Will make this option available in the next release.

**Comment by JackAdams** [comment]
In 0.7.5, the transactions collection can be specified in a `settings.json` file in the project root:
```
{
  transactionsCollection: "transactionRecords"
}
```

**Comment by stivaugoin** [comment]
Thanks!

**Comment by saliksaly** [comment]
Does not work. Client still shows error: "ncaught Error: There is already a collection named "transactions".
I think it's because the settings in settings.json is not accessible from client (it it is not in the "public" area).

**Comment by JackAdams** [comment]
Yes, I believe you're right.  I'll accept a PR and republish if there's a solution for this.

On another note, if you're using this package to deal with _money_ type transactions, I'd have to warn against it.  Using this package is a step up from no transactions, but it's not mature enough to have important data relying on its functionality.

**Comment by saliksaly** [comment]
Thank you
Yes, I've read your warning about using it in money treating apps. 
I want it for simpe purpose, for my own risk.
