### ISSUE TITLE
Issue about the Cannot read property 'transactionsCollection' of undefined

### ISSUE THREAD

**Issue by tuanhai12h** [JackAdams/meteor-transactions#48]
Hi team,

I am use this package from the version 0.7.4, but when I update to version > 0.7.5, I can not build the app both on android or iOS. 
In android, throw the error about Iron:router.
And in iOS, always loading in the splash screen.

The error catched on the verbose console is:
`I20160222-14:26:21.020(7) (android:file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js:173) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
I20160222-14:26:25.296(7) (android:http://meteor.local/packages/babrahams_transactions.js:45) Uncaught TypeError: Cannot read property 'transactionsCollection' of undefined
I20160222-14:26:26.556(7) (android:http://meteor.local/packages/global-imports.js:24) Uncaught TypeError: Cannot read property 'tx' of undefined`

After error throw, it have many Template can not seen `Uncaught ReferenceError: Template is not defined`

Please help me check or update it if this is a bug.
So many thanks team,

**Comment by JackAdams** [comment]
Try 0.7.7.  It should fix this.

**Comment by JackAdams** [comment]
Try 0.7.7 (just released on Atmosphere).  It should fix this.

**Comment by tuanhai12h** [comment]
Thanks

**Comment by JackAdams** [comment]
Did it fix the issue?  I didn't actually reproduce and test.

**Comment by tuanhai12h** [comment]
Yes, I worked.

Thanks again.

**Comment by JackAdams** [comment]
Cool. Thanks for letting me know. :-)
