### ISSUE TITLE
Please remove SimpleSchema.debug = true from source

### ISSUE THREAD

**Issue by nscarcella** [JackAdams/meteor-transactions#53]
Hello,

I noticed I was unable to turn off SimpleSchema's logs from my app's config. I tracked the problem to [this line](https://github.com/JackAdams/meteor-transactions/blob/master/lib/transactions-common.js#L1658).
The defer seems to be causing it to eval after everything else is loaded, overriding my setup.

I think it would be probably better to manage these configurations on an Application level, and don't think the debug mode is needed for anything functional, so perhaps that line can be removed for good.

The same set seems also to be [here](https://github.com/JackAdams/meteor-transactions/blob/master/lib/transactions-common-0.6.x.js#L1128).

**Comment by JackAdams** [comment]
Thanks for bringing this up.  I'll certainly remove those in the next release. (Not even sure how or why they ended up in the package code.)

**Comment by JackAdams** [comment]
0.7.12 should fix this.
