### ISSUE TITLE
Mocha server side tests fail when transactions are enabled

### ISSUE THREAD

**Issue by NickBusey** [JackAdams/meteor-transactions#71]
```
‣
Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:252:19)
    at [object Object].Transact.start (packages/babrahams_transactions.js:226:33)
    at Object.Meteor.methods.notes.remove (imports/api/notes/methods.coffee:124:8)
    at Test.<anonymous> (imports/api/notes/notes.tests.js:35:20)
    at run (packages/practicalmeteor:mocha-core/server.js:34:29)
    at Context.wrappedFunction (packages/practicalmeteor:mocha-core/server.js:63:33)
```

Disabling the transaction on the method call being called by the test, and the test passes just fine. Any ideas on how to work around this would be greatly appreciated.

**Comment by JackAdams** [comment]
This doesn't, on the surface of it, look easy to fix.  If there's a repo with a minimal repro, I could have a look at what's going on.  The trouble is, I haven't used mocha before, so I'd be poking around in the dark a bit.

**Comment by NickBusey** [comment]
I'm pretty sure if you setup a basic meteor 'todos' app and try and add a basic test to it, this will happen. I have a fairly minimal repro here.. It includes only the test from the meteor docs: https://www.meteor.com/tutorials/blaze/testing

Clone this repo: https://github.com/NickBusey/BulletNotes
Start the test: `meteor test --driver-package practicalmeteor:mocha`
Go to localhost:3000, you will see the error above.

**Comment by JackAdams** [comment]
Thanks for providing a repro.  I haven't had much success with it though:

When I try to start the app, I get:

![image](https://cloud.githubusercontent.com/assets/1647779/22274657/9786fbd6-e30c-11e6-8ef6-b5036172f694.png)

The `meteor test --driver-package practicalmeteor:mocha` command gives this:
```
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
{ [Error: ENFILE: file table overflow, uv_cwd] errno: -23, code: 'ENFILE', syscall: 'uv_cwd' }
/Users/babrahams/.meteor/packages/meteor-tool/.1.4.2_3.1ot40wu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, open '/Users/babrahams/.meteor/packages/matb33_collection-hooks/.0.8.4.1ovdyf3++os+web.browser+web.cordova/npm/node_modules/eslint-config-standard/.meteor-portable'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
...
```

I notice that one of your packages is using `matb33:collection-hooks`.  This monkey patches the same Meteor API that babrahams:transactions does.  I'd be surprised if they can actually co-exist peacefully in the same app.

**Comment by NickBusey** [comment]
Yup. I just tried this with a fresh copy of todos, added transactions to list creation, the tests worked, so it's something I'm doing. Looks good on your end, thanks!

**Comment by JackAdams** [comment]
Okay. Thanks for getting back to me about this.
