### ISSUE TITLE
Partially completed txn has mysterious state: 'complete'

### ISSUE THREAD

**Issue by Data-Meister** [JackAdams/meteor-transactions#89]
I have a transaction which has `state : 'complete'`

It has many items. Some of the items are `state : 'done'` and some of them are `state : 'pending'`

It appears as if the transaction failed to fully complete the first time around, and there may have been an attempt to recover it with `_repairAllIncomplete`

However - I can't find any situation where the library will set  `state : 'complete'` for a transaction. That's the name of a `selfRepairMode` not a transaction state, as I understand it.  

Does this ring any bells? In the meantime, I'll keep looking.

**Comment by JackAdams** [comment]
That's strange.  The line that sets the transaction state to `done` is [here](https://github.com/JackAdams/meteor-transactions/blob/master/lib/transactions-common.js#L1619).  But this should only happen if all items were successfully set to `state: done`.

I can't find anywhere in the codebase that would set a txn `state: complete`.  I'll keep looking as well.

**Comment by Data-Meister** [comment]
I found it: [here](https://github.com/JackAdams/meteor-transactions/blob/master/lib/transactions-server.js#L35)

**Comment by Data-Meister** [comment]
looks like when it's recovering from a hardware failure, it sets the state of the transaction to be the mode for recovery

**Comment by JackAdams** [comment]
Yep, you're right.  That's a bug.  I'll release a new version with a fix in the next few hours.

**Comment by Data-Meister** [comment]
Thank you so much :) 

FWIW: it seems that if `Transact.prototype._repairIncomplete` fails you get  [this line](https://github.com/JackAdams/meteor-transactions/blob/master/lib/transactions-server.js#L160)

**Comment by JackAdams** [comment]
Actually, now that I look at it, I think it might have been intentional.  It's to prevent the same transaction from being continually "repaired" on app startup if it can't actually be repaired.  The intention was (I'm guessing -- it's so long ago, I can't really remember) to set the state to something other than `pending` and to also record the type of fix attempted (`rollback` or `complete`).  In hindsight, the state should be `repairing-by-rollback` or `repairing-by-complete` or maybe just `state: repairing` with `repairMethod: rollback` or `repairMethod: complete`, until it either succeeds or fails.

I'll think about it about more and release a new version soon.

**Comment by Data-Meister** [comment]
I see, that makes sense to avoid continually retrying a repair that can't be completed. 

It might also be good to have a method for retrying failed repairs, or perhaps have a setting that enables continual retrying, or a certain number of retry attempts. 

The reason in my case the txn was failing seems to be the process running out of memory due to the sheer size of Mongo operations ( 3700 items ). In cases where it's failing because of resource overload / unreliable hardware then retrying failed repairs can make sense.

**Comment by Data-Meister** [comment]
I'd be happy to help with coding this stuff too. Let me know if you'd like any help.

**Comment by Data-Meister** [comment]
P.S. when I say "continually retry" or "retry X times" I don't mean retry immediately. I mean they'd be retried next time the app is restarted - e.g. after you've fixed a separate problem in the app that was hogging resources.

**Comment by JackAdams** [comment]
Any help with the coding would be gratefully received!

One scenario I want to avoid is: the retry attempt itself crashes the server process, the process restarts (via forever, or pm2 or systemd) and then the retry crashes it again, etc., etc.  This would be a very bad thing if it happened on a production server!

**Comment by Data-Meister** [comment]
I had a look at your latest changes - they look great, thank you so much! 

One small little thing... perhaps when calling retryFailedRepairs, it could also retry txns that crashed the process the first time around? I've submitted a [PR](https://github.com/JackAdams/meteor-transactions/pull/90) with this change.

**Comment by JackAdams** [comment]
Cool. Thanks for that.  I've just published a new version with the PR merged.
